---
# Tasks to converge to state absent
- name: flush handlers
  ansible.builtin.meta: flush_handlers

- name: Remove web server
  ansible.builtin.package:
    name: "{{ package }}"
    state: absent
